name: "Build & Release"

on:
  pull_request:
    branches:
      - dev_main
      - feature_create_build
  push:
    branches:
      - dev_main
      - feature_create_build

jobs:
  build_windows:
    name: Build & Release for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Build for Windows
        run: dart run msix:create

      - name: Zip artifacts
        run: |
          mkdir -p release
          Compress-Archive -Path build/windows/x64/runner/Release -DestinationPath release/windows_artifacts.zip

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/windows_artifacts.zip
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          "allowUpdates": true

  build_linux:
    name: Build & Release for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y clang ninja-build libgtk-3-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Build for Linux
        run: flutter build linux --release

      - name: Zip artifacts
        run: |
          mkdir -p release
          zip -r release/linux_artifacts.zip build/linux/x64/release/*

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/linux_artifacts.zip
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          "allowUpdates": true

  build_macos:
    name: Build & Release for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Build for macOS
        run: flutter build macos --release

      - name: Zip artifacts
        run: |
          mkdir -p release
          zip -r release/macos_artifacts.zip build/macos/Build/Products/Release/*

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/macos_artifacts.zip
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          "allowUpdates": true
