on:
  pull_request:
    branches:
      - main
      - new-ui
  push:
    branches:
      - main
      - new-ui
      - develop

name: "Build & Release"

jobs:
  build_windows:
    name: Build & Release for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Build for Windows
        run: flutter build windows --release

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/windows/runner/Release/*.exe
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          "allowUpdates": true

  build_linux:
    name: Build & Release for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y clang ninja-build libgtk-3-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Build for Linux
        run: flutter build linux --release

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/linux/x64/release/*.tar.gz
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          "allowUpdates": true

  build_macos:
    name: Build & Release for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Build for macOS
        run: flutter build macos --release

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/macos/Build/Products/Release/*.app
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          "allowUpdates": true
